package com.example.shoppinglist

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "shopping_item")   // this is table name
data class ShoppingItem (
    @ColumnInfo(name = "item_name")   // this is column name in table
    var name : String,
    @ColumnInfo(name = "item_count")
    var count : Int
){
    @PrimaryKey(autoGenerate = true)  // primary key will be autogenerated, this is why it is not added in constructor
    var id: Int? = null
}